name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version if you need to build the project

      - name: Build project (if needed)
        run: |
          # Run build commands here, if applicable
          # e.g., npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web # Replace this with the path to the directory you want to deploy
